### ISSUE TITLE
How to send messages to spawned worlds?

### ISSUE THREAD

**Issue by dented42** [tonyg/minimart#2]
I'm trying to spawn a process in a world, but I don't seem to be able to send a message to the process inside that world. Based on the examples I would have thought it would require the listening process to have a meta-level of 1, but that doesn't seem to work.

A simple example of demonstrating my confusion can be found at https://gist.github.com/dented42/5d22e580728f06959b60

What am I doing wrong?

**Comment by tonyg** [comment]
Your program there is 99.9% correct.

What is happening is that the initial `ping-msg` is being sent before the `inside` actor has established its subscription. It's perhaps best to think of all the actors in the system as running asynchronously once started. That is, even though *actions* are processed in order, including spawn actions, one should think of the resulting *actors* as running in an arbitrary order.

If you replace the last line (`(send (ping-msg 'out 'in))`) of your program with the following actor, your program runs fine:

````racket
(actor #:name kick-things-off
       ;; 0) I wait for a ping-listener to arrive
       (observe-subscribers (ping-msg ? ?)
         #:presence ping-listeners-present?
         (when ping-listeners-present?
           (list (send (ping-msg 'out 'in)) ; 1) I send ping to inside
                 (quit)))))
````
